import localFont from "next/font/local";
import Loading from "@/components/Loading";
import "./globals.css";
import { FloatingNavDemo } from "@/components/navigationBar";

const geistSans = localFont({
  src: "../../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const iceland = localFont({
  src: "../../public/fonts/iceland-latin-400-normal.woff",
  variable: "--font-geist-iceland",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${iceland.variable} antialiased`}
      >
        <FloatingNavDemo />
        {children}
      </body>
    </html>
  );
}
