// src/app/layout.js (or src/pages/_app.js)
import localFont from "next/font/local";
import Loading from "@/components/Loading"; // Import the Loading component
import "./globals.css";
import { FloatingNavDemo } from "@/components/navigationBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FloatingNavDemo />
        {children}
      </body>
    </html>
  );
}
