// src/app/layout.js
import localFont from "next/font/local";
import Loading from "@/components/Loading"; // Import the Loading component
import "./globals.css"; // Import global styles
import { FloatingNavDemo } from "@/components/navigationBar";

// Load local fonts
const geistSans = localFont({
  src: "../../public/fonts/GeistVF.woff", // Ensure the path to the font is correct
  variable: "--font-geist-sans",
  weight: "100 900", // Specify the weight range
});

const iceland = localFont({
  src: "../../public/fonts/iceland-latin-400-normal.woff", // Ensure the path to the font is correct
  variable: "--font-geist-iceland",
  weight: "100 900", // Specify the weight range
});

const geistMono = localFont({
  src: "../../public/fonts/GeistMonoVF.woff", // Ensure the path to the font is correct
  variable: "--font-geist-mono",
  weight: "100 900", // Specify the weight range
});

// Metadata for the application
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${iceland.variable} antialiased`} // Apply font variables to the body
      >
        <FloatingNavDemo /> {/* Navigation component */}
        {children} {/* Render child components */}
      </body>
    </html>
  );
}
